apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    spec:
      tolerations:
        - key: "key"
          operator: "Equal"
          value: "value"
          effect: "NoExecute"
          tolerationSeconds: 3600